name: Test

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Run check
      run: |
        ./gradlew check -x test
    - name: Run tests
      run: |
        ./gradlew test
